import 'dotenv/config'
import {PrismaClient} from '@prisma/client'
import slugify from 'slugify'

const prisma=new PrismaClient()
const sources={
 britannica:'Encyclopaedia Britannica',
 un:'United Nations',
 unesco:'UNESCO',
 who:'World Health Organization',
 mit:'MIT Technology Review'
}
const categories=[
 ['Cameroon','People, places, history, culture, and ideas from Cameroon.'],
 ['Africa','Stories and context from across the African continent.'],
 ['Technology','Technology, digital life, science, and innovation.'],
 ['History','Events, people, and turning points that shaped the world.'],
 ['Art & Artists','Artists, movements, objects, and visual culture.'],
 ['Travel','Culture-led journeys and destinations.'],
 ['Philosophy','Ideas and thinkers that challenge how we understand the world.'],
 ['Stories','Unexpected stories from past and present.']
]
const posts=[
 {title:'Cameroon in One Landscape: From Atlantic Coast to Highland Grasslands',category:'cameroon',excerpt:'A geographic tour of the country’s coast, forest, savanna, and volcanic highlands.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/place/Cameroon',image:'/assets/history.svg',body:'Cameroon is often described as a country where several African environments meet. The Atlantic coast, dense southern forests, central plateaus, northern savannas, and western highlands create different rhythms of work, food, travel, and memory.\n\nThat variety is more than a scenic detail. It helps explain why the country contains such a wide range of ecological knowledge and cultural traditions. A thoughtful journey through Cameroon begins by noticing how quickly the landscape changes, and how communities adapt to each setting.'},
 {title:'Why Mount Cameroon Shapes More Than the Skyline',category:'cameroon',excerpt:'The country’s highest mountain is also a story about climate, farming, travel, and observation.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/place/Mount-Cameroon',image:'/assets/history.svg',body:'Mount Cameroon rises above the southwest coast as one of the most recognizable landmarks in the country. Its volcanic terrain and heavy rainfall influence farming systems, local routes, and the way visitors understand the region.\n\nThe mountain also offers a reminder that geography is never passive. Soil, water, altitude, and weather shape livelihoods, while the communities around the mountain turn those conditions into practical knowledge passed from one generation to the next.'},
 {title:'The Wouri Estuary and the Name Cameroon',category:'cameroon',excerpt:'A name associated with prawns became the name of a country through centuries of travel and political change.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/place/Cameroon',image:'/assets/history.svg',body:'Place names often carry several histories at once. Cameroon’s name is connected to the Wouri estuary and to early Portuguese descriptions of the area. Over time, the word travelled from a river and coastal setting into maps, colonial administrations, and eventually the modern country.\n\nStudying a name this way helps us see geography as a record of encounters. Rivers and ports are not just points on a map; they are places where language, commerce, power, and memory meet.'},
 {title:'Cameroon’s Four Seasons of Rain and Dryness',category:'cameroon',excerpt:'Climate varies sharply from the coast to the far north, and that variation shapes everyday life.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/place/Cameroon/Climate',image:'/assets/history.svg',body:'Cameroon’s climate changes with latitude and elevation. Coastal areas receive intense rainfall, while the northern regions experience a longer dry season. Between them are highlands and plateaus with their own weather patterns.\n\nFor farmers, travellers, builders, and families planning daily work, these differences are practical knowledge. Climate is read through clouds, roads, planting calendars, rivers, and the timing of markets. A map of rainfall is therefore also a map of lived experience.'},
 {title:'A Continent of Many Regions, Not One Story',category:'africa',excerpt:'Africa’s scale makes simple descriptions misleading. Its regions reveal different histories, climates, and futures.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/place/Africa',image:'/assets/history.svg',body:'Africa is a continent of extraordinary geographic and cultural range. The Mediterranean north, the Sahel, the equatorial forest belt, the eastern highlands, and the southern regions each connect people to different environments and historical routes.\n\nGood continental storytelling should resist flattening that variety. It should make room for local histories, city life, rural knowledge, languages, creative industries, and the links between African communities and the wider world.'},
 {title:'How African Cities Turn Movement Into Culture',category:'africa',excerpt:'Markets, migration, music, and public space give cities their own creative language.',sourceName:sources.un,sourceUrl:'https://www.un.org/africarenewal/',image:'/assets/art.svg',body:'African cities are often discussed through population figures, but numbers do not fully describe how urban culture is made. It emerges in transport corridors, markets, neighbourhood studios, street fashion, food stalls, radio, and informal gathering places.\n\nMovement is part of the creative process. People carry sounds, recipes, languages, and business ideas between regions. The result is not a single urban culture but a collection of local experiments that continue to change.'},
 {title:'The Sahel as a Meeting Ground',category:'africa',excerpt:'The Sahel is both an ecological zone and a long-standing corridor of exchange.',sourceName:sources.un,sourceUrl:'https://www.un.org/africarenewal/tags/sahel',image:'/assets/history.svg',body:'The Sahel is frequently presented only through crisis headlines. A longer view shows a region defined by movement, adaptation, trade, scholarship, and relationships between desert and grassland.\n\nIts history is a reminder that borders and climate zones do not erase human connection. Communities have developed ways to respond to uncertain rainfall and changing routes, while cities and learning centres have linked the region to wider networks for centuries.'},
 {title:'African Languages and the Work of Memory',category:'africa',excerpt:'Language carries family history, humour, place knowledge, and ways of seeing the world.',sourceName:sources.un,sourceUrl:'https://www.un.org/africarenewal/magazine',image:'/assets/philosophy.svg',body:'Language is one of the most durable forms of cultural memory. A proverb can hold an argument, a greeting can locate a relationship, and a place name can preserve a landscape that has changed.\n\nAcross Africa, multilingual life is ordinary rather than exceptional. Supporting local languages in education, media, technology, and publishing is therefore not only a cultural project; it is also a way to make public life more accessible and more representative.'},
 {title:'Artificial Intelligence Is More Than a Chatbot',category:'technology',excerpt:'AI includes systems for learning, reasoning, perception, language, and specialised decision-making.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/technology/artificial-intelligence',image:'/assets/technology.svg',body:'Artificial intelligence is best understood as a family of techniques rather than one product. Some systems classify images, some recommend information, some translate language, and others help researchers search large collections of data.\n\nThe useful question is not whether a machine is generally intelligent. It is what a particular system can do, what data shaped it, where it fails, and who remains responsible for the decision. That framing makes conversations about AI more concrete and less theatrical.'},
 {title:'Why Digital Tools Need Local Context',category:'technology',excerpt:'A tool designed for one environment may fail when language, infrastructure, and daily habits change.',sourceName:sources.mit,sourceUrl:'https://www.technologyreview.com/',image:'/assets/technology.svg',body:'Technology travels, but it does not arrive in a vacuum. Connectivity, payment systems, language, trust, electricity, and the cost of devices all affect how a product is used.\n\nThe best digital tools are often those that pay attention to these conditions early. Local context is not a constraint to work around after launch; it is part of product design. It can determine whether an idea becomes useful infrastructure or remains an impressive demo.'},
 {title:'The Human Skill Behind Good Online Research',category:'technology',excerpt:'Search engines are powerful, but careful research still depends on comparison and judgment.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/technology/search-engine',image:'/assets/technology.svg',body:'Online research feels instant because search engines organise enormous collections of information. Yet finding a result is only the beginning. Readers still need to compare dates, identify the author, inspect the evidence, and distinguish a primary source from a repeated claim.\n\nThese habits are especially important when technology makes polished misinformation easy to produce. Research is not simply retrieval; it is the patient work of deciding what deserves confidence.'},
 {title:'What Makes a Digital Archive Useful?',category:'technology',excerpt:'A good archive connects reliable metadata, clear navigation, and long-term care.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/memory-world',image:'/assets/technology.svg',body:'Digital archives are often imagined as large stores of files. In practice, their value depends on context. A photograph needs a date, a place, a creator, and a description. A document needs a clear relationship to the collection around it.\n\nThe most useful archive is therefore not always the biggest. It is the one that helps a reader understand what they are seeing and gives future researchers enough information to continue the work.'},
 {title:'World War II and the Shape of the Modern World',category:'history',excerpt:'The conflict changed borders, institutions, technology, and the balance of global power.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/event/World-War-II',image:'/assets/history.svg',body:'World War II was a global conflict whose effects reached far beyond the battlefield. It transformed political borders, accelerated technological change, displaced millions, and helped create a new international order.\n\nStudying the war responsibly means holding several scales together: decisions by governments, the experience of civilians, the violence of occupation, resistance, genocide, and the difficult political settlements that followed. The past remains relevant because its institutions and wounds continue to shape the present.'},
 {title:'Why Rivers Matter in the History of Civilizations',category:'history',excerpt:'Rivers have carried food, people, trade, stories, and political power across centuries.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/science/river',image:'/assets/history.svg',body:'Rivers make movement possible, but they also create boundaries and obligations. Settlements grow around reliable water, farmers learn the timing of floods, and rulers compete to control crossings and irrigation.\n\nA river history is therefore never only about geography. It is a history of engineering, labour, belief, trade, and negotiation. Following a river through time can reveal how a society organised itself and what it considered worth protecting.'},
 {title:'The Archive Is Never Neutral',category:'history',excerpt:'What survives in a collection depends on power, preservation, and the choices of earlier generations.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/memory-world',image:'/assets/history.svg',body:'Archives feel authoritative because they preserve traces of the past. But every archive has gaps. Some voices were never recorded, some materials were destroyed, and some collections were assembled by institutions with particular interests.\n\nReading an archive well means asking both what a document says and why it survived. That second question does not make history impossible; it makes historical work more honest and more attentive to people who are missing from the record.'},
 {title:'Maps Tell Stories Through Their Borders',category:'history',excerpt:'A map is an argument about what matters, where places begin, and how movement should be understood.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/science/cartography',image:'/assets/history.svg',body:'Maps appear precise, but every map selects. Scale leaves something out, labels prioritise certain names, and borders turn complex relationships into lines.\n\nThat does not make maps useless. It makes them readable cultural objects. Comparing maps from different periods can show how governments imagined territory, how explorers described unfamiliar places, and how communities defended their own names for the world around them.'},
 {title:'Why Artists Return to the Same Subjects',category:'art-and-artists',excerpt:'Repetition can be a method of seeing rather than a lack of imagination.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/art/art',image:'/assets/art.svg',body:'An artist may paint the same landscape, figure, or object many times because each attempt changes the question. Light shifts, memory interrupts observation, and a familiar subject reveals a new formal problem.\n\nRepetition also creates a record of attention. Looking across a series allows us to see not only the finished images but the artist’s changing relationship with time, material, and uncertainty.'},
 {title:'The Workshop Behind the Masterpiece',category:'art-and-artists',excerpt:'Many celebrated works were shaped by studios, assistants, patrons, and systems of practice.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/art/Western-painting/Italy',image:'/assets/art.svg',body:'The idea of the solitary genius is compelling, but much art has always been collaborative. Workshops trained apprentices, prepared materials, repeated designs, and managed commissions for demanding patrons.\n\nSeeing the workshop does not diminish the artist. It reveals the social and technical conditions that made ambitious work possible. It also gives us a richer history of labour, skill, and creative organisation.'},
 {title:'How Museums Decide What to Put on Display',category:'art-and-artists',excerpt:'Exhibitions are acts of selection, interpretation, and invitation.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/museums',image:'/assets/art.svg',body:'A museum gallery is never the whole collection. Curators choose objects, arrange relationships, write labels, and decide what visitors should notice first. Those decisions turn storage into an argument about history and meaning.\n\nGood exhibitions make their choices visible. They give objects room to speak while also acknowledging provenance, uncertainty, and the people whose histories may have been overlooked.'},
 {title:'A Short History of the Portrait',category:'art-and-artists',excerpt:'Portraits have recorded identity, status, intimacy, and political power in many forms.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/art/portrait-art',image:'/assets/art.svg',body:'A portrait can be a likeness, but it can also be a performance. Clothing, posture, setting, and objects all communicate how a person wants to be seen or how a patron wants them remembered.\n\nFrom painted panels to photographs and digital images, portraiture remains a negotiation between presence and representation. The face is only one part of the story.'},
 {title:'Travel Slowly Through a City',category:'travel',excerpt:'The most memorable journeys often begin when a visitor stops trying to see everything.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/culture',image:'/assets/history.svg',body:'Fast travel encourages lists. Slow travel encourages attention. A neighbourhood market, a bus route, a courtyard, or a conversation can teach more about a city than a checklist of landmarks.\n\nMoving slowly also changes the ethics of travel. Visitors have more time to notice local businesses, listen to residents, and understand that a destination is a home before it is a backdrop.'},
 {title:'What Makes a Place Feel Like Home?',category:'travel',excerpt:'Belonging is built from routine, memory, welcome, and the small details of everyday life.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/culture',image:'/assets/art.svg',body:'Travel writing often focuses on what is new to the visitor. A different question asks what is ordinary to the people who live there. The smell of a morning meal, the sound of a local radio station, and the route to a familiar shop can reveal the texture of a place.\n\nThese details make travel writing more generous. They shift attention from collecting experiences to understanding relationships.'},
 {title:'The Philosophy of a Good Question',category:'philosophy',excerpt:'Questions can open inquiry, expose assumptions, and make difficult conversations more precise.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/topic/Socratic-method',image:'/assets/philosophy.svg',body:'A good question does not always seek a quick answer. It can reveal that two people are using the same word differently, or that a confident conclusion rests on an untested assumption.\n\nThe questioning tradition associated with Socrates remains useful because it treats thought as a shared activity. Inquiry becomes less about winning and more about discovering what we actually mean.'},
 {title:'Can Technology Help Us Pay Better Attention?',category:'philosophy',excerpt:'Digital tools can reduce friction, but attention still needs intention and boundaries.',sourceName:sources.britannica,sourceUrl:'https://www.britannica.com/technology/social-media',image:'/assets/technology.svg',body:'Technology is often blamed for distraction, but the deeper issue is design. Many digital systems are built to keep us returning, while our own goals may require quiet, patience, and unfinished time.\n\nA better relationship with technology begins by asking what an application is helping us do. The answer may be communication, learning, or work; it may also be simple entertainment. Clarity about the purpose makes boundaries easier to choose.'},
 {title:'The Joy of Learning Without an Exam',category:'stories',excerpt:'Curiosity does not need a certificate to be valuable.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/education',image:'/assets/philosophy.svg',body:'Learning outside formal assessment is one of the quiet pleasures of adult life. A reader follows a question because it is interesting, a traveller learns a few words because they matter, or a family preserves a recipe because it connects generations.\n\nThis kind of learning is not less serious. It is simply guided by attention rather than grades, and it often continues long after a classroom would have closed.'},
 {title:'How Food Carries a Family Story',category:'stories',excerpt:'Recipes preserve movement, adaptation, and the people who taught us how to make them.',sourceName:sources.unesco,sourceUrl:'https://www.unesco.org/en/intangible-cultural-heritage',image:'/assets/art.svg',body:'A recipe can look like a list of instructions, but it often contains a map of family life. Ingredients change when people move, techniques adjust to new kitchens, and a dish acquires new meaning at birthdays, ceremonies, and ordinary dinners.\n\nWriting about food well means writing about people. The most memorable detail is often not the ingredient itself but who prepared it, who learned the method, and why the dish still matters.'}
]
const paragraphHtml=text=>text.split('\n\n').map(paragraph=>`<p>${paragraph}</p>`).join('')
for(const [name,description] of categories)await prisma.category.upsert({where:{slug:name==='Art & Artists'?'art-and-artists':slugify(name,{lower:true,strict:true})},update:{description},create:{name,slug:name==='Art & Artists'?'art-and-artists':slugify(name,{lower:true,strict:true}),description}})
const admin=await prisma.user.findUnique({where:{email:'admin@example.com'}})
if(!admin)throw new Error('Seed the admin account before loading launch content.')
for(const [index,post] of posts.entries()){
 const category=await prisma.category.findUnique({where:{slug:post.category}})
 const slug=slugify(post.title,{lower:true,strict:true})
 const content=`${paragraphHtml(post.body)}<p><strong>Further reading:</strong> <a href="${post.sourceUrl}" target="_blank" rel="noreferrer">${post.sourceName}</a></p>`
 const image=post.image.replace('/assets/technology.svg','/assets/art.svg')
 await prisma.post.upsert({where:{slug},update:{excerpt:post.excerpt,content,featuredImage:image,sourceName:post.sourceName,sourceUrl:post.sourceUrl,status:'PUBLISHED',publishedAt:new Date(Date.now()-index*86400000),categoryId:category.id},create:{title:post.title,slug,excerpt:post.excerpt,content,featuredImage:image,featuredImageAlt:post.title,sourceName:post.sourceName,sourceUrl:post.sourceUrl,status:'PUBLISHED',featured:index<3,publishedAt:new Date(Date.now()-index*86400000),authorId:admin.id,categoryId:category.id}})
}
console.log(`Loaded ${posts.length} original, source-linked launch posts.`)
await prisma.$disconnect()
