import SiteSeo from './components/SiteSeo'
import {textColor} from './colors'
import {getSiteSettings} from './settings'
import AuthorRequests from './pages/admin/AuthorRequests'
import {Routes,Route,useLocation,Navigate} from 'react-router-dom'
import {useEffect,useState} from 'react'
import Header from './components/Header';import Footer from './components/Footer'
import Home from './pages/Home';import Category from './pages/Category';import Article from './pages/Article';import About from './pages/About';import Search from './pages/Search';import AuthorRequest from './pages/AuthorRequest';import Legal from './pages/Legal'
import Login from './pages/admin/Login';import AdminLayout from './pages/admin/AdminLayout';import Dashboard from './pages/admin/Dashboard';import Posts from './pages/admin/Posts';import PostEditor from './pages/admin/PostEditor';import Categories from './pages/admin/Categories';import Users from './pages/admin/Users';import Settings from './pages/admin/Settings';import Media from './pages/admin/Media';import Newsletter from './pages/admin/Newsletter';import Profile from './pages/admin/Profile';import Comments from './pages/admin/Comments'
import Adverts from './pages/admin/Adverts'
function Guard({children}){return localStorage.getItem('cms_token')?children:<Navigate to="/admin" replace/>}
export default function App(){const [site,setSite]=useState(null);useEffect(()=>{getSiteSettings().then(setSite);const update=e=>setSite(e.detail);window.addEventListener('site-settings-updated',update);return()=>window.removeEventListener('site-settings-updated',update)},[]);useEffect(()=>{const color=/^#[0-9a-f]{6}$/i.test(site?.brandColor||'')?site.brandColor:'#17344e';document.documentElement.style.setProperty('--brand-color',color);document.documentElement.style.setProperty('--brand-contrast',textColor(color,site?.ctaTextColor))},[site?.brandColor,site?.ctaTextColor]);const loc=useLocation();const admin=loc.pathname.startsWith('/admin');useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'instant'})},[loc.pathname])
if(!admin&&site?.maintenanceMode)return <><SiteSeo site={site}/><main className="container page-pad"><h1>We will be back soon</h1><p>Our publication is undergoing maintenance. Please check back shortly.</p><a href="/admin">Staff sign in</a></main></>;
return <><SiteSeo site={site}/>{!admin&&<Header/>}<Routes>
<Route path="/" element={<Home/>}/><Route path="/category/:slug" element={<Category/>}/><Route path="/article/:slug" element={<Article/>}/><Route path="/about" element={<About/>}/><Route path="/search" element={<Search/>}/><Route path="/author-request" element={<AuthorRequest/>}/><Route path="/terms" element={<Legal type="terms"/>}/><Route path="/privacy" element={<Legal type="privacy"/>}/><Route path="/cookies" element={<Legal type="cookies"/>}/>
<Route path="/admin" element={<Login/>}/><Route path="/admin/*" element={<Guard><AdminLayout/></Guard>}><Route path="dashboard" element={<Dashboard/>}/><Route path="posts" element={<Posts/>}/><Route path="posts/new" element={<PostEditor/>}/><Route path="posts/:id" element={<PostEditor/>}/><Route path="categories" element={<Categories/>}/><Route path="author-requests" element={<AuthorRequests/>}/><Route path="adverts" element={<Adverts/>}/><Route path="media" element={<Media/>}/><Route path="newsletter" element={<Newsletter/>}/><Route path="comments" element={<Comments/>}/><Route path="users" element={<Users/>}/><Route path="profile" element={<Profile/>}/><Route path="settings" element={<Settings/>}/></Route>
<Route path="*" element={<main className="container page-pad"><h1>Page not found</h1><p>This page is not available.</p><a href="/">Explore the latest stories</a></main>}/></Routes>{!admin&&<Footer/>}</>}
