import {useEffect,useState} from 'react'
import api from '../../api'
import './Management.css'
export default function AuthorRequests(){
 const [data,setData]=useState({items:[],pages:1,emailEnabled:false});const [status,setStatus]=useState('');const [query,setQuery]=useState('');const [page,setPage]=useState(1);const [form,setForm]=useState(null);const [role,setRole]=useState('AUTHOR');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [revision,setRevision]=useState(0)
 useEffect(()=>{let cancelled=false;api.get('/admin/author-requests',{params:{status,q:query,page}}).then(r=>{if(!cancelled)setData(r.data)}).catch(e=>{if(!cancelled)setError(e.response?.data?.message||'Could not load applications.')});return()=>{cancelled=true}},[status,query,page,revision])
 function choose(item){setForm({...item});setPassword('');setRole('AUTHOR');setMessage('');setError('')}
 async function save(e){e.preventDefault();await run(async()=>{const r=await api.put('/admin/author-requests/'+form.id,{status:form.status,response:form.response});setForm(r.data);return 'Review saved.'})}
 async function run(action){setBusy(true);setError('');setMessage('');try{setMessage(await action());setRevision(n=>n+1)}catch(e){setError(e.response?.data?.message||'The action failed. Please try again.')}finally{setBusy(false)}}
 async function send(){if(!confirm(`Send this reply to ${form.email}?`))return;await run(async()=>{const r=await api.post('/admin/author-requests/'+form.id+'/reply',{response:form.response},{timeout:30000});return r.data.message})}
 async function create(e){e.preventDefault();await run(async()=>{const r=await api.post('/admin/author-requests/'+form.id+'/account',{role,password});setForm(current=>({...current,accountId:r.data.user.id,status:'APPROVED'}));setPassword('');return r.data.message})}
 return <div><div className="admin-title"><div><h1>Author requests</h1><p>Review applications, reply to contributors and create accounts.</p></div></div><div className="management-filters"><label>Search applicants<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All requests</option>{['PENDING','REVIEWING','APPROVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></label></div>{error&&<div role="alert" className="alert">{error}</div>}{message&&<div role="status" className="success">{message}</div>}
 <div className="request-grid"><div className="request-list">{data.items.map(item=><button type="button" disabled={busy} aria-pressed={form?.id===item.id} key={item.id} onClick={()=>choose(item)}><strong>{item.name}</strong><small>{item.email}</small><small>{item.status} · {new Date(item.createdAt).toLocaleDateString()}</small></button>)}{!data.items.length&&<p>No applications match your filters.</p>}<div className="pagination"><button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {data.pages}</span><button disabled={page>=data.pages||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>
 {form?<section className="panel request-detail"><h2>{form.name}</h2><a href={'mailto:'+form.email}>{form.email}</a><h3>Biography</h3><p>{form.bio}</p><h3>Story pitch</h3><p>{form.pitch}</p>{/^https?:\/\//i.test(form.portfolioUrl||'')&&<a href={form.portfolioUrl} target="_blank" rel="noopener noreferrer">Open portfolio</a>}
 <form onSubmit={save}><fieldset disabled={busy} className="management-fieldset"><label>Review status<select aria-label="Review status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['PENDING','REVIEWING','APPROVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></label><label>Reply<textarea rows="7" maxLength="10000" value={form.response||''} onChange={e=>setForm({...form,response:e.target.value})}/></label><div className="management-actions"><button className="primary">Save review & draft</button><button type="button" disabled={!data.emailEnabled||!form.response?.trim()} onClick={send}>Send email reply</button><a href={`mailto:${form.email}?subject=${encodeURIComponent('Your contributor application')}&body=${encodeURIComponent(form.response||'')}`}>Open email app</a></div></fieldset></form>
 {!data.emailEnabled&&<p className="field-note">Server email is not configured. You can save a draft and send it using Open email app.</p>}
 <h3>Create contributor account</h3>{form.accountId?<p>This application is linked to an account. Manage it under Accounts.</p>:<form onSubmit={create}><fieldset disabled={busy} className="management-fieldset"><label>Role<select aria-label="Role" value={role} onChange={e=>setRole(e.target.value)}><option>AUTHOR</option><option>EDITOR</option></select></label><p className="field-note">Authors write their own drafts. Editors review and publish content across the site.</p><label>Initial password<input type="password" autoComplete="new-password" required minLength="12" maxLength="72" value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="field-note">Share the login details securely. Account creation does not email the password.</p><button className="primary">Approve & create account</button></fieldset></form>}
 <h3>Email history</h3>{(data.items.find(item=>item.id===form.id)?.replies||form.replies||[]).map(reply=><div key={reply.id} className="request-reply"><small>{reply.status} · {new Date(reply.sentAt||reply.createdAt).toLocaleString()}</small><p>{reply.body}</p></div>)}
 </section>:<div className="panel">Select an application to review it.</div>}</div></div>
}
