import {useEffect,useState} from 'react'
import api from '../../api'

const maxSize=5*1024*1024
export default function Media(){
 const [items,setItems]=useState([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [focus,setFocus]=useState({x:50,y:50})
 const load=()=>api.get('/admin/media').then(r=>setItems(r.data)).catch(e=>setError(e.response?.data?.message||'Could not load media'))
 useEffect(()=>{load()},[])
 async function upload(e){const file=e.target.files?.[0]; if(!file)return; setError(''); if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))return setError('Use JPEG, PNG, WEBP, or GIF images.'); if(file.size>maxSize)return setError('Images must be 5 MB or smaller.'); setBusy(true); try{await api.post('/admin/media/upload',file,{headers:{'Content-Type':file.type,'X-File-Type':file.type,'X-File-Name':file.name,'X-Alt-Text':file.name.replace(/\.[^.]+$/,'') ,'X-Focal-Point':JSON.stringify(focus)}});await load();e.target.value=''}catch(err){setError(err.response?.data?.message||'Upload failed. Configure Cloudinary in backend/.env.')}finally{setBusy(false)}}
 async function remove(id){if(confirm('Delete this media record?')){await api.delete('/admin/media/'+id);setItems(items.filter(item=>item.id!==id))}}
 return <div><div className="admin-title"><div><h1>Media library</h1><p>Upload safe, optimized images and manage editorial assets.</p></div><label className="primary upload-button">{busy?'Uploading...':'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} disabled={busy}/></label></div>{error&&<div className="alert">{error}</div>}<div className="panel crop-panel"><strong>Crop focus</strong><p>Choose the focal point used when images are cropped into cards. Maximum upload size: 5 MB.</p><div className="crop-controls"><label>Horizontal<input type="range" min="0" max="100" value={focus.x} onChange={e=>setFocus({...focus,x:e.target.value})}/></label><label>Vertical<input type="range" min="0" max="100" value={focus.y} onChange={e=>setFocus({...focus,y:e.target.value})}/></label></div></div><div className="media-grid">{items.map(item=><article className="media-card" key={item.id}><div className="media-preview"><img src={item.url} alt={item.altText||item.name} style={{objectPosition:`${focus.x}% ${focus.y}%`}}/></div><strong>{item.name}</strong><small>{item.width||'?'} × {item.height||'?'} · {item.mimeType||'image'}</small>{['ADMIN','SUPER_ADMIN'].includes(JSON.parse(localStorage.getItem('cms_user')||'{}').role)&&<button className="text-danger" onClick={()=>remove(item.id)}>Delete</button>}</article>)}</div></div>
}
