import {useEffect,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import api from '../../api'
import './Management.css'
export default function Posts(){
 const [params,setParams]=useSearchParams();const [result,setResult]=useState({items:[],total:0,page:1,pages:1});const [cats,setCats]=useState([]);const [authors,setAuthors]=useState([]);const [selected,setSelected]=useState([]);const [bulk,setBulk]=useState('DRAFT');const [error,setError]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0)
 const role=JSON.parse(localStorage.getItem('cms_user')||'{}').role;const canPublish=role!=='AUTHOR';const query=params.toString()
 useEffect(()=>{api.get('/categories').then(r=>setCats(r.data)).catch(()=>{});api.get('/admin/posts/authors').then(r=>setAuthors(r.data)).catch(()=>{})},[])
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');setSelected([]);api.get('/admin/posts?'+query).then(r=>{if(!cancelled)setResult(r.data)}).catch(e=>{if(!cancelled)setError(e.response?.data?.message||'Could not load posts.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[query,revision])
 function filter(key,value){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key!=='page')next.set('page','1');setParams(next,{replace:true})}
 async function remove(p){if(!confirm(`Permanently delete “${p.title}”? This cannot be undone.`))return;setBusy(true);setError('');try{await api.delete('/admin/posts/'+p.id);setMessage('Post deleted.');setRevision(n=>n+1)}catch(e){setError(e.response?.data?.message||'Could not delete post.')}finally{setBusy(false)}}
 async function applyBulk(){if(!confirm(`Set ${selected.length} selected posts to ${bulk.toLowerCase()}?`))return;setBusy(true);setError('');try{const r=await api.post('/admin/posts/bulk',{ids:selected,status:bulk});setMessage(`${r.data.count} posts updated.`);setRevision(n=>n+1)}catch(e){setError(e.response?.data?.message||'Could not update posts.')}finally{setBusy(false)}}
 async function exportCsv(){setBusy(true);setError('');try{const r=await api.get('/admin/posts/export?'+query,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='posts-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){let message='Could not export posts.';try{message=JSON.parse(await e.response.data.text()).message||message}catch{}setError(message)}finally{setBusy(false)}}
 const dropdown=(label,key,options)=><label>{label}<select aria-label={label} value={params.get(key)||''} onChange={e=>filter(key,e.target.value)}><option value="">All</option>{options.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select></label>
 return <div><div className="admin-title"><div><h1>{canPublish?'Posts':'My posts'}</h1><p>{canPublish?'Manage publication content and review author drafts.':'Write your drafts. Editors review and publish your stories.'}</p></div><Link className="primary" to="/admin/posts/new">New post</Link></div>
 <div className="management-filters"><label>Search<input value={params.get('q')||''} placeholder="Title, slug or excerpt" onChange={e=>filter('q',e.target.value)}/></label>{dropdown('Status','status',['DRAFT','PUBLISHED','ARCHIVED'].map(s=>[s,s]))}{dropdown('Category','categoryId',[['none','Uncategorized'],...cats.map(c=>[c.id,c.name])])}{canPublish&&dropdown('Author','authorId',authors.map(a=>[a.id,a.name]))}{dropdown('Featured','featured',[['true','Featured'],['false','Not featured']])}<label>Created from<input type="date" value={params.get('from')||''} onChange={e=>filter('from',e.target.value)}/></label><label>Created to<input type="date" value={params.get('to')||''} onChange={e=>filter('to',e.target.value)}/></label><label>Sort by<select value={params.get('sort')||'updatedAt'} onChange={e=>filter('sort',e.target.value)}>{[['updatedAt','Last updated'],['createdAt','Date created'],['title','Title'],['viewCount','Views'],['seoScore','SEO score']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>Direction<select value={params.get('direction')||'desc'} onChange={e=>filter('direction',e.target.value)}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><button type="button" onClick={()=>setParams({})}>Reset filters</button></div>
 {error&&<div className="alert" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
 <div className="management-actions"><button onClick={exportCsv} disabled={busy||loading}>Export filtered CSV</button><button onClick={()=>setRevision(n=>n+1)} disabled={busy||loading}>Refresh</button>{canPublish&&<><span>{selected.length} selected</span><select aria-label="Bulk status" value={bulk} onChange={e=>setBulk(e.target.value)}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button disabled={!selected.length||busy||loading} onClick={applyBulk}>Apply status</button></>}</div>
 <div className="table-wrap" aria-busy={loading}><table><thead><tr>{canPublish&&<th><input type="checkbox" aria-label="Select all posts on this page" disabled={loading||busy||!result.items.length} checked={!!result.items.length&&selected.length===result.items.length} onChange={e=>setSelected(e.target.checked?result.items.map(p=>p.id):[])}/></th>}<th>Title</th><th>Status</th><th>Views</th><th>SEO</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="management-empty">Loading posts…</td></tr>:result.items.length?result.items.map(p=><tr key={p.id}>{canPublish&&<td><input type="checkbox" aria-label={`Select ${p.title}`} disabled={busy} checked={selected.includes(p.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,p.id]:current.filter(id=>id!==p.id))}/></td>}<td><strong>{p.title}</strong>{p.featured&&<span title="Featured"> ★</span>}<small className="post-category">{p.category?.name||'Uncategorized'} · {p.author?.name}</small></td><td><span className={'badge '+p.status.toLowerCase()}>{p.status}</span></td><td>{p.viewCount}<small className="post-category">{p.likeCount} likes · {p.commentCount} comments</small></td><td>{p.seoScore??'—'}</td><td>{new Date(p.updatedAt).toLocaleDateString()}</td><td>{(canPublish||p.status==='DRAFT')&&<><Link to={'/admin/posts/'+p.id}>Edit</Link> · <button disabled={busy} className="text-danger" onClick={()=>remove(p)}>Delete</button></>}{p.status==='PUBLISHED'&&<> · <Link to={'/article/'+p.slug} target="_blank">View</Link></>}</td></tr>):<tr><td colSpan="7" className="management-empty">No posts match these filters.</td></tr>}</tbody></table></div>
 <div className="pagination"><span>{result.total} posts · Page {result.page} of {result.pages}</span><label>Per page<select value={params.get('pageSize')||20} onChange={e=>filter('pageSize',e.target.value)}>{[10,20,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button disabled={loading||result.page<=1} onClick={()=>filter('page',String(result.page-1))}>Previous</button><button disabled={loading||result.page>=result.pages} onClick={()=>filter('page',String(result.page+1))}>Next</button></div></div>
}
