import {useEffect,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import api from '../../api'
import RichTextEditor from '../../components/RichTextEditor'

const empty={title:'',slug:'',excerpt:'',content:'',featuredImage:'',featuredImageAlt:'',status:'DRAFT',categoryId:'',seoTitle:'',seoDescription:'',seoFocusKeyword:'',featured:false,contentFormat:'html'}
const maxImageSize=5*1024*1024
const imageTypes=['image/jpeg','image/png','image/webp','image/gif']
export default function PostEditor(){
 const isAuthor=JSON.parse(localStorage.getItem('cms_user')||'{}').role==='AUTHOR';
 const {id}=useParams();const nav=useNavigate();const [p,setP]=useState(empty);const [cats,setCats]=useState([]);const [seo,setSeo]=useState({score:0,checks:[]});const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{api.get('/categories').then(r=>setCats(r.data));if(id)api.get('/admin/posts/'+id).then(r=>{setP({...empty,...r.data,categoryId:r.data.categoryId||''});setSeo({score:r.data.seoScore||0,checks:r.data.seoChecks||[]})}).catch(e=>setError(e.response?.data?.message||'Could not load post'))},[id])
 function set(key,value){setP(current=>({...current,[key]:value}))}
 function valid(file){if(!imageTypes.includes(file.type)||file.size>maxImageSize){setError('Use JPEG, PNG, WEBP, or GIF images under 5 MB.');return false}return true}
 async function upload(e){const file=e.target.files?.[0];if(!file||!valid(file))return;try{const r=await api.post('/admin/media/upload',file,{headers:{'Content-Type':file.type,'X-File-Type':file.type,'X-File-Name':file.name,'X-Alt-Text':p.featuredImageAlt||file.name.replace(/\.[^.]+$/,'')}});set('featuredImage',r.data.url);setError('')}catch(err){setError(err.response?.data?.message||'Featured image upload failed. Configure Cloudinary.')}}
 async function uploadInline(file){if(!file||!valid(file))return;try{const r=await api.post('/admin/media/upload',file,{headers:{'Content-Type':file.type,'X-File-Type':file.type,'X-File-Name':file.name,'X-Alt-Text':file.name.replace(/\.[^.]+$/,'')}});const alt=file.name.replace(/\.[^.]+$/,'');setError('');return {src:r.data.url,alt}}catch(err){setError(err.response?.data?.message||'Inline image upload failed')}}
 async function analyze(){try{const r=await api.post('/admin/posts/seo-analyze',p);setSeo(r.data)}catch(err){setError(err.response?.data?.message||'SEO analysis failed')}}
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const r=id?await api.put('/admin/posts/'+id,p):await api.post('/admin/posts',p);setSeo(r.data.seo||seo);nav('/admin/posts')}catch(err){setError(err.response?.data?.message||'Could not save post')}finally{setSaving(false)}}
 if(isAuthor&&p.status!=='DRAFT')return <div className="panel">Published and archived stories are managed by editors.</div>;
 return <form onSubmit={save}><div className="admin-title"><div><h1>{id?'Edit post':'New post'}</h1><p>Build a structured article with featured and inline images.</p></div><div className="editor-actions"><button type="button" onClick={analyze}>Analyze SEO</button><button className="primary" disabled={saving}>{saving?'Saving...':'Save post'}</button></div></div>{error&&<div className="alert">{error}</div>}<div className="editor-grid"><section className="panel"><label>Title<input value={p.title} onChange={e=>set('title',e.target.value)} required/></label><label>Slug<input value={p.slug} onChange={e=>set('slug',e.target.value)} placeholder="auto-generated if empty"/></label><label>Excerpt<textarea rows="3" value={p.excerpt||''} onChange={e=>set('excerpt',e.target.value)}/></label><RichTextEditor key={id||'new'} value={p.content} onChange={content=>setP(current=>({...current,content,contentFormat:'html'}))} onUploadImage={uploadInline}/></section><aside className="editor-sidebar"><section className="panel"><label>Status<select value={p.status} onChange={e=>set('status',e.target.value)}><option>DRAFT</option>{!isAuthor&&<><option>PUBLISHED</option><option>ARCHIVED</option></>}</select></label><label>Category<select value={p.categoryId} onChange={e=>set('categoryId',e.target.value)}><option value="">Select category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="checkbox"><input type="checkbox" disabled={isAuthor} checked={!!p.featured} onChange={e=>set('featured',e.target.checked)}/> Featured story</label></section><section className="panel seo-panel"><div className="seo-score"><strong>{seo.score}</strong><span>/ 100 SEO score</span></div><label>Focus keyword<input value={p.seoFocusKeyword||''} onChange={e=>set('seoFocusKeyword',e.target.value)}/></label><label>SEO title<input value={p.seoTitle||''} onChange={e=>set('seoTitle',e.target.value)} maxLength="60"/></label><label>Meta description<textarea rows="4" value={p.seoDescription||''} onChange={e=>set('seoDescription',e.target.value)} maxLength="160"/></label><ul className="seo-checks">{seo.checks.map(check=><li className={check.pass?'pass':''} key={check.key}>{check.pass?'✓':'○'} {check.label}</li>)}</ul></section><section className="panel"><label>Featured image<input type="file" accept={imageTypes.join(',')} onChange={upload}/></label>{p.featuredImage&&<img className="editor-image-preview" src={p.featuredImage} alt={p.featuredImageAlt||'Featured preview'}/>}<label>Image alt text<input value={p.featuredImageAlt||''} onChange={e=>set('featuredImageAlt',e.target.value)} placeholder="Describe the image"/></label><p className="field-note">Safe formats: JPEG, PNG, WEBP, GIF. Maximum 5 MB.</p></section></aside></div></form>
}
