import {useEffect,useState} from 'react'
import api from '../../api'
import {refreshSiteSettings} from '../../settings'
import SiteLogo from '../../components/SiteLogo'
import './Management.css'
const defaults={siteName:'',tagline:'',contactEmail:'',logoText:'',logoUrl:'',footerText:'',defaultSeoTitle:'',defaultSeoDescription:'',googleAnalyticsId:'',brandColor:'#17344e',allowComments:false,maintenanceMode:false,customCss:'',customHead:'',socialLinks:{}}
const tabs=['Basic settings','Branding','SEO & analytics','Footer & social','Publishing','Advanced']
export default function Settings(){
 const [settings,setSettings]=useState(defaults);const [tab,setTab]=useState(tabs[0]);const [message,setMessage]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false)
 useEffect(()=>{api.get('/admin/settings').then(r=>setSettings({...defaults,...r.data,socialLinks:r.data.socialLinks||{}})).catch(()=>setError('Could not load settings. Reload to try again.')).finally(()=>setLoading(false))},[])
 function set(key,value){setSettings(current=>({...current,[key]:value}));setMessage('')}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api.put('/admin/settings',settings);await refreshSiteSettings();setMessage('Settings saved.')}catch(e){setError(e.response?.data?.message||'Could not save settings.')}finally{setBusy(false)}}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>5*1024*1024){setError('Choose a JPEG, PNG, WEBP or GIF up to 5 MB.');return}setBusy(true);setError('');try{const r=await api.post('/admin/media/upload',file,{headers:{'Content-Type':file.type,'X-File-Type':file.type,'X-File-Name':file.name}});set('logoUrl',r.data.url)}catch(e){setError(e.response?.data?.message||'Logo upload failed.')}finally{setBusy(false)}}
 const input=(label,key,type='text',max)=> <label>{label}<input type={type} maxLength={max} value={settings[key]||''} onChange={e=>set(key,e.target.value)}/></label>
 const text=(label,key)=> <label>{label}<textarea rows="4" value={settings[key]||''} onChange={e=>set(key,e.target.value)}/></label>
 return <form onSubmit={save} className="management-settings"><div className="admin-title"><div><h1>Settings</h1><p>Manage your publication’s identity and preferences.</p></div><button className="primary" disabled={busy||loading}>Save settings</button></div>
 {error&&<div className="alert" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
 <div className="management-tabs" role="tablist" aria-label="Settings sections">{tabs.map((name,index)=><button type="button" role="tab" id={`settings-tab-${index}`} aria-selected={tab===name} aria-controls={`settings-panel-${index}`} tabIndex={tab===name?0:-1} key={name} onClick={()=>setTab(name)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(index+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[next]);document.getElementById(`settings-tab-${next}`).focus()}}}>{name}</button>)}</div>
 {loading?<p>Loading settings...</p>:<fieldset disabled={busy} className="management-fieldset"><section className="panel" role="tabpanel" id={`settings-panel-${tabs.indexOf(tab)}`} aria-labelledby={`settings-tab-${tabs.indexOf(tab)}`}>
 {tab===tabs[0]&&<>{input('Site name','siteName')}{input('Tagline','tagline')}{input('Contact email','contactEmail','email')}</>}
 {tab===tabs[1]&&<><h2>Publication logo</h2><div className="logo-preview wordmark"><SiteLogo site={settings}/></div><label>Upload logo<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload}/></label><p className="field-note">A transparent PNG or WEBP works well. Maximum 5 MB. Save settings after uploading.</p>{settings.logoUrl&&<button type="button" onClick={()=>set('logoUrl','')}>Remove image logo</button>}{input('Fallback logo text','logoText')}{input('Brand color','brandColor','color')}<p>The image appears in the header and footer. Text appears if the image is missing or fails to load.</p></>}
 {tab===tabs[2]&&<>{input('Default SEO title','defaultSeoTitle','text',60)}{text('Default SEO description','defaultSeoDescription')}{input('Google Analytics ID','googleAnalyticsId')}<p className="field-note">Use a title up to 60 characters and a description around 160 characters.</p></>}
 {tab===tabs[3]&&<>{text('Footer description','footerText')}<h2>Social links</h2>{['facebook','instagram','linkedin','youtube','x'].map(key=><label key={key}>{key}<input type="url" placeholder="https://" value={settings.socialLinks[key]||''} onChange={e=>set('socialLinks',{...settings.socialLinks,[key]:e.target.value})}/></label>)}<p className="field-note">The footer automatically lists your categories. Empty social links are hidden.</p></>}
 {tab===tabs[4]&&<><label className="checkbox"><input type="checkbox" checked={settings.allowComments} onChange={e=>set('allowComments',e.target.checked)}/> Accept new comments</label><p>New comments require editorial approval.</p><label className="checkbox"><input type="checkbox" checked={settings.maintenanceMode} onChange={e=>set('maintenanceMode',e.target.checked)}/> Maintenance mode</label><p className="field-note">The public site displays a maintenance message while staff can still sign in.</p></>}
 {tab===tabs[5]&&<>{text('Custom CSS','customCss')}{text('Head markup','customHead')}<h2>Author reply delivery</h2><p>Email replies use the server’s SMTP configuration. Credentials are managed in the server environment, never in public site settings.</p></>}
 </section></fieldset>}</form>
}
