import {useEffect,useState} from 'react'
import api from '../../api'
import {refreshSiteSettings} from '../../settings'
const defaults={siteName:'',tagline:'',contactEmail:'',logoText:'',footerText:'',defaultSeoTitle:'',defaultSeoDescription:'',googleAnalyticsId:'',brandColor:'#17344e',allowComments:false,maintenanceMode:false,customCss:'',customHead:''}
export default function Settings(){
 const [settings,setSettings]=useState(defaults);const [message,setMessage]=useState('')
 useEffect(()=>{api.get('/settings').then(response=>setSettings({...defaults,...response.data}))},[])
 function set(key,value){setSettings(current=>({...current,[key]:value}))}
 async function save(event){event.preventDefault();await api.put('/admin/settings',settings);await refreshSiteSettings();setMessage('Settings saved')}
 return <form className="settings-panel" onSubmit={save}><div className="admin-title"><div><h1>Advanced settings</h1><p>Control identity, search defaults, analytics, accessibility, and custom presentation.</p></div><button className="primary">Save settings</button></div>{message&&<div className="alert">{message}</div>}<div className="settings-grid"><section className="panel"><h3>Publication identity</h3><label>Site name<input value={settings.siteName} onChange={e=>set('siteName',e.target.value)}/></label><label>Tagline<input value={settings.tagline} onChange={e=>set('tagline',e.target.value)}/></label><label>Logo text<input value={settings.logoText} onChange={e=>set('logoText',e.target.value)}/></label><label>Contact email<input type="email" value={settings.contactEmail} onChange={e=>set('contactEmail',e.target.value)}/></label><label>Footer text<textarea rows="3" value={settings.footerText} onChange={e=>set('footerText',e.target.value)}/></label></section><section className="panel"><h3>Search and analytics</h3><label>Default SEO title<input value={settings.defaultSeoTitle||''} onChange={e=>set('defaultSeoTitle',e.target.value)}/></label><label>Default SEO description<textarea rows="4" value={settings.defaultSeoDescription||''} onChange={e=>set('defaultSeoDescription',e.target.value)}/></label><label>Google Analytics ID<input placeholder="G-XXXXXXXXXX" value={settings.googleAnalyticsId||''} onChange={e=>set('googleAnalyticsId',e.target.value)}/></label><label>Brand color<input type="color" value={settings.brandColor||'#17344e'} onChange={e=>set('brandColor',e.target.value)}/></label></section><section className="panel"><h3>Editorial controls</h3><label className="checkbox"><input type="checkbox" checked={!!settings.allowComments} onChange={e=>set('allowComments',e.target.checked)}/> Allow comments</label><label className="checkbox"><input type="checkbox" checked={!!settings.maintenanceMode} onChange={e=>set('maintenanceMode',e.target.checked)}/> Maintenance mode</label></section><section className="panel"><h3>Custom code</h3><label>Head markup<textarea rows="5" value={settings.customHead||''} onChange={e=>set('customHead',e.target.value)}/></label><label>Custom CSS<textarea rows="7" value={settings.customCss||''} onChange={e=>set('customCss',e.target.value)}/></label></section></div></form>
}
